#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝ 
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝  
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║   
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝   
#	vidy007 - https://github.com/vidy007/dotfiles

import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]


live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = true
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
#opacity = 0.8
dynamic_padding = true

[window.padding]
x = 40
y = 40

[scrolling]
history = 10000
multiplier = 3

#useless:
[bell]
animation = "EaseOutQuad"
duration = 1
command = "neofetch"
