[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

# Cursor colors
[colors.cursor]
cursor = "#ebdbb2"
text = "#282828"

# Normal colors
[colors.normal]
black = "#282828"
blue = "#83a598"
cyan = "#689d6a"
green = "#98971a"
magenta = "#d3869b"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"

# Bright colors
[colors.bright]
black = "#1d2021"
blue = "#458588"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#b16286"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"
