[font]
size = 12

builtin_box_drawing = true

normal = { family = "JetBrainsMono", style = "Regular" }
bold = { family = "JetBrainsMono", style = "Bold" }
italic = { family = "JetBrainsMono", style = "Italic" }
bold_italic = { family = "JetBrainsMono", style = "Bold Italic" }
